services:
    app:
        ports:
            - 'CUSTOM_PORT:8088'
        volumes:
            - .:/workspace
            - /workspace/__pycache__
    db:
        ports:
            - '5432'
    pgadmin:
        ports:
            - '5433'
